import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useDeferredValue, useState } from "react";
import { ExportMenu } from "../components/ExportMenu";
import { ReceiptTable } from "../components/ReceiptTable";
import { ReceiptUploader } from "../components/ReceiptUploader";
import { useReceipts } from "../hooks/useReceipts";
export const DashboardPage = () => {
    const [merchant, setMerchant] = useState("");
    const [status, setStatus] = useState("");
    const deferredMerchant = useDeferredValue(merchant);
    const filters = {
        merchant: deferredMerchant || undefined,
        status: status || undefined
    };
    const { data, isLoading } = useReceipts(filters);
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("section", { className: "grid gap-6 xl:grid-cols-[1.1fr_0.9fr]", children: [_jsxs("div", { className: "rounded-[2rem] border border-white/70 bg-white/70 p-8 shadow-panel backdrop-blur", children: [_jsx("p", { className: "font-mono text-xs uppercase tracking-[0.35em] text-tide", children: "Receipt Radar" }), _jsx("h1", { className: "mt-4 max-w-2xl font-display text-5xl font-semibold tracking-tight text-ink", children: "Turn paper receipts into a clean, searchable expense ledger." }), _jsx("p", { className: "mt-5 max-w-2xl text-base leading-7 text-slate-600", children: "Capture a receipt, extract merchant and totals with OCR, review line items, and export the finished records to CSV or Excel." }), _jsxs("div", { className: "mt-8 flex flex-wrap gap-3", children: [_jsx("div", { className: "rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white", children: "React + Tailwind" }), _jsx("div", { className: "rounded-full bg-ember px-4 py-2 text-sm font-medium text-white", children: "OCR Ready" }), _jsx("div", { className: "rounded-full bg-tide px-4 py-2 text-sm font-medium text-white", children: "CSV/XLSX Export" })] })] }), _jsxs("div", { className: "rounded-[2rem] border border-slate-200 bg-slate-950 p-8 text-white shadow-panel", children: [_jsx("p", { className: "font-mono text-xs uppercase tracking-[0.3em] text-emerald-300", children: "Flow" }), _jsxs("ol", { className: "mt-5 space-y-4 text-sm text-slate-300", children: [_jsx("li", { children: "1. Upload or photograph the receipt." }), _jsx("li", { children: "2. Server preprocesses the image and runs OCR." }), _jsx("li", { children: "3. Parsed fields are stored for review." }), _jsx("li", { children: "4. User corrects anything uncertain and exports the data." })] })] })] }), _jsx(ReceiptUploader, {}), _jsxs("section", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx("input", { value: merchant, onChange: (event) => setMerchant(event.target.value), placeholder: "Filter by merchant", className: "rounded-full border border-slate-200 bg-white/85 px-4 py-3 text-sm shadow-panel" }), _jsxs("select", { value: status, onChange: (event) => setStatus(event.target.value), className: "rounded-full border border-slate-200 bg-white/85 px-4 py-3 text-sm shadow-panel", children: [_jsx("option", { value: "", children: "All statuses" }), _jsx("option", { value: "processed", children: "Processed" }), _jsx("option", { value: "needs_review", children: "Needs review" }), _jsx("option", { value: "failed", children: "Failed" })] })] }), _jsx(ExportMenu, { filters: filters })] }), isLoading ? _jsx("div", { className: "rounded-[2rem] bg-white/90 p-6 shadow-panel", children: "Loading receipts..." }) : _jsx(ReceiptTable, { receipts: data?.data ?? [] })] }));
};
